### ISSUE TITLE
Logs are not inserted when the app is closing or if the app crashes

### ISSUE THREAD

**Issue by sekulicb** [vip32/serilog-sinks-litedb#13]
Hi. Thanks for the library.

To reproduce the steps:

1. Create WPF app on .net core 3.1
2. Add Application Exit event in App.xaml
3. Add "Global exception handler" to the start up of the app and hook up to AppDomain.CurrentDomain.UnhandledException / Application.Current.DispatcherUnhandledException / TaskScheduler.UnobservedTaskException etc..
4. Inform the user that the app crashed and let it crash

Scenario number 1
- Start the app
- Click on "x" button in a corner
- App is closing, putting breakpoint on Application Exit to make sure it does happen, but when I say "log some information", that string is never inserted in the database

Scenario number 2
- Start the app
- Call some method that will throw unhandled exception
- Some of the events that we hooked up in global ex class fire
- Again log.error the type of the error for example, but it never gets inserted

Can you confirm the behaviour that I described here?

**Comment by sekulicb** [comment]
Closing since looks like this library is no longer actively maintained....

**Comment by vip32** [comment]
Sorry not really active on this repo, you got a PR which can be merged?
