### ISSUE TITLE
Add support for rolling files

### ISSUE THREAD

**Issue by ti24horas** [vip32/serilog-sinks-litedb#2]
Is it possible to support rolling files for lite db sink?
Suppose we need to troubleshoot an app (and the app is writing verbose). By using a LiteDbExplorer for example, one could download the log to local machine and run queries without impact the application.
The rolling file support allows older logs to be deleted or archived (and later be consolidated) without impact a running application.

**Comment by vip32** [comment]
PRs are welcome 🤗
