### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by ti24horas** [vip32/serilog-sinks-litedb#3]
Allow this library to be compiled into .net core (1.1 and maybe 2.0)

Can I use vs2017 for that? or old (and vs2015 supported) project.json?

**Comment by vip32** [comment]
Yes vs2017, project.json is dead

**Comment by ti24horas** [comment]
@vip32 when you have time, can you take a look?

**Comment by mzorec** [comment]
Are there any plans to support .net core?

**Comment by vip32** [comment]
done, now netstandard 2.0 is supported
