### ISSUE TITLE
nuget package outdated

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [vip32/serilog-sinks-litedb#8]
The nuget package is from November 11th 2016, while you updated the code last August 25th 2017. The current nuget package also throws an error:

> Exception while emitting periodic batch from Serilog.Sinks.MongoDB.Sinks.LiteDB.LiteDBSink: System.MissingMethodException: Method not found: 'Void LiteDB.LiteDatabase..ctor(System.String, LiteDB.BsonMapper)'.
   at Serilog.Sinks.MongoDB.Sinks.LiteDB.LiteDBSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()

**Comment by gilbertlol** [comment]
Hi @vip32 have you planned to update the nuget package?

**Comment by bunomonteiro** [comment]
any news?

**Comment by chris-kwng** [comment]
Too bad that nothing happens anymore. **#yetanotherdeadproject**

**Comment by vip32** [comment]
Yes, we are all busy :) but let me have a look at it....

**Comment by vip32** [comment]
Yes, we are all busy :) but let me take a look at it...

**Comment by chris-kwng** [comment]
i have already fixed it

https://www.dropbox.com/s/7rnmd65778710cy/serilog-sinks-litedb-updated.zip?dl=0

**Comment by vip32** [comment]
thx, will also upgrade it to netstandard 2.0 + fix the build > nuget issue

**Comment by CKoewing** [comment]
Do you know a simple way to convert a log entry from the LiteDB collection into an object?

My class ...

```
public class LogEntry
{
	[BsonField("_id")]
	public ObjectId Id { get; set; }
	[BsonField("_t")]
	public DateTime Time { get; set; }
	[BsonField("_ty")]
	public int Year { get; set; }
	[BsonField("_tm")]
	public int Month { get; set; }
	[BsonField("_td")]
	public int Day { get; set; }
	[BsonField("_tw")]
	public int Week { get; set; }
	[BsonField("_m")]
	public string Title { get; set; }
	[BsonField("_mt")]
	public string Description { get; set; }
	[BsonField("_i")]
	public string Index { get; set; }
	[BsonField("_l")]
	public string Level { get; set; }
}
```

... and the following code ...
```

using (var db = new LiteDatabase($"filename={Path.Combine(BasicSettings.AppPath, "Logs.db")};Mode=ReadOnly"))
{
	var col = db.GetCollection<LogEntry>(Program.Settings.TaskName);
	var data = col.FindAll().OrderBy(x => x.Time);

	foreach (var log in data)
	{
		test = log.Time;
	}
}

```

... does not work, but the field names should be right.

**Comment by vip32** [comment]
all done, get it here: https://www.nuget.org/packages/Serilog.Sinks.LiteDB/1.0.17
